import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cayo Perico Heist Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
        <h1 className={styles.title}>
          Welcome to Cayo Perico Heist Calculator
        </h1>
          <Image
          src="/images/TheCayoPericoHeist.jpg"
          height={1080}
          width={1920}
          layout='fixed'
          alt="Header Pic">
          </Image>
        </div>  
        <p className={styles.description}>
         Here you will find all the information on the heist and can calculate the amount of people to invite to heist, the value that you can get and the elite challenge criteria.
        </p>

        <div className={styles.grid}>
          <a href="https://gta.fandom.com/wiki/The_Cayo_Perico_Heist" className={styles.card}>
            <h2>The Cayo Perico Heist</h2>
            <p>Everything you need to know from start to finish.
              Gtafandom wiki article.
            </p>
          </a>

          <a href="/values" className={styles.card}>
            <h2>The bags and targets</h2>
            <p>Learn about the values of all targets and filling of the bags!</p>
          </a>

          <a
            href="/calculator"
            className={styles.card}
          >
            <h2>The mansion Calculator</h2>
            <p>Calculate your particular recon and target values. Find out how many people you need to invite.</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        SiimonHyarm 2022
      </footer>
    </div>
  )
}
